/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import cromwell.client.model.FailureMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CallMetadata
 */
public class CallMetadataTest {
    private final CallMetadata model = new CallMetadata();

    /**
     * Model tests for CallMetadata
     */
    @Test
    public void testCallMetadata() {
        // TODO: test CallMetadata
    }

    /**
     * Test the property 'inputs'
     */
    @Test
    public void inputsTest() {
        // TODO: test inputs
    }

    /**
     * Test the property 'executionStatus'
     */
    @Test
    public void executionStatusTest() {
        // TODO: test executionStatus
    }

    /**
     * Test the property 'backend'
     */
    @Test
    public void backendTest() {
        // TODO: test backend
    }

    /**
     * Test the property 'backendStatus'
     */
    @Test
    public void backendStatusTest() {
        // TODO: test backendStatus
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'failures'
     */
    @Test
    public void failuresTest() {
        // TODO: test failures
    }

    /**
     * Test the property 'returnCode'
     */
    @Test
    public void returnCodeTest() {
        // TODO: test returnCode
    }

    /**
     * Test the property 'stdout'
     */
    @Test
    public void stdoutTest() {
        // TODO: test stdout
    }

    /**
     * Test the property 'stderr'
     */
    @Test
    public void stderrTest() {
        // TODO: test stderr
    }

    /**
     * Test the property 'backendLogs'
     */
    @Test
    public void backendLogsTest() {
        // TODO: test backendLogs
    }

}
