/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FormDataWorkflowTypeParam
 */
public class FormDataWorkflowTypeParamTest {
    /**
     * Model tests for FormDataWorkflowTypeParam
     */
    @Test
    public void testFormDataWorkflowTypeParam() {
        // TODO: test FormDataWorkflowTypeParam
    }

}
