/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import cromwell.client.model.DefaultWorkflowEngineParameter;
import cromwell.client.model.WorkflowTypeVersion;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceInfoAllOf
 */
public class ServiceInfoAllOfTest {
    private final ServiceInfoAllOf model = new ServiceInfoAllOf();

    /**
     * Model tests for ServiceInfoAllOf
     */
    @Test
    public void testServiceInfoAllOf() {
        // TODO: test ServiceInfoAllOf
    }

    /**
     * Test the property 'workflowTypeVersions'
     */
    @Test
    public void workflowTypeVersionsTest() {
        // TODO: test workflowTypeVersions
    }

    /**
     * Test the property 'supportedWesVersions'
     */
    @Test
    public void supportedWesVersionsTest() {
        // TODO: test supportedWesVersions
    }

    /**
     * Test the property 'supportedFilesystemProtocols'
     */
    @Test
    public void supportedFilesystemProtocolsTest() {
        // TODO: test supportedFilesystemProtocols
    }

    /**
     * Test the property 'workflowEngineVersions'
     */
    @Test
    public void workflowEngineVersionsTest() {
        // TODO: test workflowEngineVersions
    }

    /**
     * Test the property 'defaultWorkflowEngineParameters'
     */
    @Test
    public void defaultWorkflowEngineParametersTest() {
        // TODO: test defaultWorkflowEngineParameters
    }

    /**
     * Test the property 'systemStateCounts'
     */
    @Test
    public void systemStateCountsTest() {
        // TODO: test systemStateCounts
    }

    /**
     * Test the property 'authInstructionsUrl'
     */
    @Test
    public void authInstructionsUrlTest() {
        // TODO: test authInstructionsUrl
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
