/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import cromwell.client.model.ValueType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ValueTypeObjectFieldTypesInner
 */
public class ValueTypeObjectFieldTypesInnerTest {
    private final ValueTypeObjectFieldTypesInner model = new ValueTypeObjectFieldTypesInner();

    /**
     * Model tests for ValueTypeObjectFieldTypesInner
     */
    @Test
    public void testValueTypeObjectFieldTypesInner() {
        // TODO: test ValueTypeObjectFieldTypesInner
    }

    /**
     * Test the property 'fieldName'
     */
    @Test
    public void fieldNameTest() {
        // TODO: test fieldName
    }

    /**
     * Test the property 'fieldType'
     */
    @Test
    public void fieldTypeTest() {
        // TODO: test fieldType
    }

}
