/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import cromwell.client.model.DescriptorTypeAndVersion;
import cromwell.client.model.ToolInputParameter;
import cromwell.client.model.ToolOutputParameter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowDescription
 */
public class WorkflowDescriptionTest {
    private final WorkflowDescription model = new WorkflowDescription();

    /**
     * Model tests for WorkflowDescription
     */
    @Test
    public void testWorkflowDescription() {
        // TODO: test WorkflowDescription
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'validWorkflow'
     */
    @Test
    public void validWorkflowTest() {
        // TODO: test validWorkflow
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'inputs'
     */
    @Test
    public void inputsTest() {
        // TODO: test inputs
    }

    /**
     * Test the property 'outputs'
     */
    @Test
    public void outputsTest() {
        // TODO: test outputs
    }

    /**
     * Test the property 'submittedDescriptorType'
     */
    @Test
    public void submittedDescriptorTypeTest() {
        // TODO: test submittedDescriptorType
    }

    /**
     * Test the property 'isRunnableWorkflow'
     */
    @Test
    public void isRunnableWorkflowTest() {
        // TODO: test isRunnableWorkflow
    }

    /**
     * Test the property 'importedDescriptorTypes'
     */
    @Test
    public void importedDescriptorTypesTest() {
        // TODO: test importedDescriptorTypes
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'parameterMeta'
     */
    @Test
    public void parameterMetaTest() {
        // TODO: test parameterMeta
    }

}
