/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowTypeVersion
 */
public class WorkflowTypeVersionTest {
    private final WorkflowTypeVersion model = new WorkflowTypeVersion();

    /**
     * Model tests for WorkflowTypeVersion
     */
    @Test
    public void testWorkflowTypeVersion() {
        // TODO: test WorkflowTypeVersion
    }

    /**
     * Test the property 'workflowTypeVersion'
     */
    @Test
    public void workflowTypeVersionTest() {
        // TODO: test workflowTypeVersion
    }

}
