---
apiVersion: v1
kind: Service
metadata:
  name: cromwell
  labels:
    app: cromwell
spec:
  type: LoadBalancer
  selector:
    app: cromwell
  ports:
    - protocol: TCP
      port: 8000
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cromwell
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cromwell
    spec:
      containers:
        - name: cromwell
          image: broadinstitute/cromwell:40
          command: ["java"]
          args: ["-jar", "/app/cromwell.jar", "server"]
          ports:
            - containerPort: 8010
          livenessProbe:
            httpGet:
              path: /engine/v1/status
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
