CREATE TABLE TMP_SYMBOL
(
  TMP_SYMBOL_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  WORKFLOW_EXECUTION_UUID VARCHAR(100) NOT NULL,
  SYMBOL_NAME VARCHAR(100),
  SYMBOL_SCOPE VARCHAR(255),
  SYMBOL_INDEX INT,
  SYMBOL_ATTEMPT INT,
  WDL_VALUE LONGTEXT,
  WDL_TYPE VARCHAR(100)
);
