INSERT INTO METADATA_JOURNAL (
  WORKFLOW_EXECUTION_UUID,
  METADATA_KEY,
  METADATA_VALUE,
  METADATA_VALUE_TYPE,
  METADATA_TIMESTAMP
)
  SELECT
    WORKFLOW_EXECUTION_UUID,
    'submittedFiles:workflow',
    wea.WDL_SOURCE,
    'string',
    NOW()
  FROM WORKFLOW_EXECUTION_AUX wea
    JOIN WORKFLOW_EXECUTION we ON we.WORKFLOW_EXECUTION_ID = wea.WORKFLOW_EXECUTION_ID;

INSERT INTO METADATA_JOURNAL (
  WORKFLOW_EXECUTION_UUID,
  METADATA_KEY,
  METADATA_VALUE,
  METADATA_VALUE_TYPE,
  METADATA_TIMESTAMP
)
  SELECT
    WORKFLOW_EXECUTION_UUID,
    'submittedFiles:inputs',
    wea.JSON_INPUTS,
    'string',
    NOW()
  FROM WORKFLOW_EXECUTION_AUX wea
    JOIN WORKFLOW_EXECUTION we ON we.WORKFLOW_EXECUTION_ID = wea.WORKFLOW_EXECUTION_ID;

INSERT INTO METADATA_JOURNAL (
  WORKFLOW_EXECUTION_UUID,
  METADATA_KEY,
  METADATA_VALUE,
  METADATA_VALUE_TYPE,
  METADATA_TIMESTAMP
)
  SELECT
    WORKFLOW_EXECUTION_UUID,
    'submittedFiles:options',
    wea.WORKFLOW_OPTIONS,
    'string',
    NOW()
  FROM WORKFLOW_EXECUTION_AUX wea
    JOIN WORKFLOW_EXECUTION we ON we.WORKFLOW_EXECUTION_ID = wea.WORKFLOW_EXECUTION_ID;
