#!/bin/bash

cd /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


cd /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution



out19f376d1="${tmpDir}/out.$$" err19f376d1="${tmpDir}/err.$$"
mkfifo "$out19f376d1" "$err19f376d1"
trap 'rm "$out19f376d1" "$err19f376d1"' EXIT
touch '/cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution/stdout' '/cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution/stderr'
tee '/cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution/stdout' < "$out19f376d1" &
tee '/cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution/stderr' < "$err19f376d1" >&2 &
(
cd /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution


echo "44"
)  > "$out19f376d1" 2> "$err19f376d1"
echo $? > /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution
sync


)
mv /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution/rc.tmp /cromwell-executions/struct_literal/19f376d1-c4aa-454f-bcdd-0cc93b7946f5/call-a/execution/rc
