swagger: '2.0'
info:
  title: Cromwell
  description: One workflow service to rule them all...
  contact:
    email: dsde@broadinstitute.org
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  termsOfService: 'http://www.github.com/broadinstitute/cromwell'
produces:
  - application/json
paths:
  '/workflows/{version}/{id}/abort':
    post:
      summary: Abort a workflow based on workflow id
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: id
          description: workflow identifier
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
          schema:
            $ref: '#/definitions/WorkflowAbortResponse'
        '400':
          description: Malformed Workflow ID
        '403':
          description: Workflow in terminal status
        '404':
          description: Workflow ID Not Found
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
  '/workflows/{version}':
    post:
      summary: Submit a new workflow for execution
      consumes:
        - multipart/form-data
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: wdlSource
          description: WDL Source
          required: true
          type: file
          in: formData
        - name: workflowInputs
          description: WDL JSON
          required: true
          type: file
          in: formData
      tags:
        - Workflows
      responses:
        '201':
          description: Successful Request
          schema:
            $ref: '#/definitions/WorkflowSubmitResponse'
        '400':
          description: Malformed Input
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
  '/workflows/{version}/validate':
    post:
      summary: Validate a workflow for execution
      consumes:
        - multipart/form-data
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: wdlSource
          description: WDL Source
          required: true
          type: file
          in: formData
        - name: workflowInputs
          description: WDL JSON
          required: true
          type: file
          in: formData
      tags:
         - Workflows
      responses:
        '200':
          description: Successful Request
          schema:
            $ref: '#/definitions/WorkflowValidateResponse'
        '400':
          description: Malformed Input
          schema:
            $ref: '#/definitions/WorkflowValidateResponse'
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
  '/workflows/{version}/{id}/outputs':
    get:
      summary: Query for workflow outputs based on workflow id
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
        - name: id
          description: Workflow Identifier
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
        '400':
          description: Malformed Workflow ID
        '404':
          description: Workflow ID Not Found
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
  '/workflows/{version}/{workflowId}/outputs/{callFqn}':
    get:
      summary: Query for call outputs based on workflow id and call fully qualified name
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: workflowId
          description: Workflow ID
          required: true
          type: string
          in: path
        - name: callFqn
          description: Call fully qualified name
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
        '400':
          description: Malformed Workflow ID
        '404':
          description: Call Fully Qualified Name Not Found
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
  '/workflows/{version}/{id}/status':
    get:
      summary: Query for workflow status based on workflow id
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: id
          description: Workflow Identifier
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
          schema:
            $ref: '#/definitions/WorkflowStatusResponse'
        '400':
          description: Malformed Workflow ID
        '404':
          description: Workflow ID Not Found
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
  '/workflows/{version}/{workflowId}/logs/{callFqn}':
    get:
      summary: Query standard output and error of a call from its fully qualified name
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: workflowId
          description: Workflow ID
          required: true
          type: string
          in: path
        - name: callFqn
          description: Call fully qualified name
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
        '400':
          description: Malformed Workflow ID
        '404':
          description: Call Fully Qualified Name Not Found
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
  '/workflows/{version}/{workflowId}/logs':
    get:
      summary: Query for the standard output and error of all calls in a workflow
      parameters:
        - name: version
          description: API Version
          required: true
          type: string
          in: path
          default: v1
        - name: workflowId
          description: Workflow ID
          required: true
          type: string
          in: path
      tags:
        - Workflows
      responses:
        '200':
          description: Successful Request
        '400':
          description: Malformed Workflow ID
        '404':
          description: Workflow ID Not Found
        '500':
          description: Internal Error
      security:
        - google_oauth:
            - openid
securityDefinitions:
  google_oauth:
    type: oauth2
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    flow: implicit
    scopes:
      openid: open id authorization
definitions:
  WorkflowValidateResponse:
    description: ''
    required:
      - valid
    properties:
      valid:
        type: boolean
        description: The validation of the workflow
      error:
        type: string
        description: The validation error of the workflow
  WorkflowSubmitResponse:
    description: ''
    required:
      - id
      - status
    properties:
      id:
        type: string
        description: The identifier of the workflow
      status:
        type: string
        description: The status of the workflow
  WorkflowAbortResponse:
    description: ''
    required:
      - id
      - status
    properties:
      id:
        type: string
        description: The identifier of the workflow
      status:
        type: string
        description: The status of the workflow
  WorkflowStatusResponse:
    description: ''
    required:
      - id
      - status
    properties:
      id:
        type: string
        description: The identifier of the workflow
      status:
        type: string
        description: The status of the workflow