/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.api;

import cromwell.client.ApiException;
import cromwell.client.model.StatusResponse;
import cromwell.client.model.VersionResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EngineApi
 */
@Disabled
public class EngineApiTest {

    private final EngineApi api = new EngineApi();

    /**
     * Return the current health status of any monitored subsystems
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void engineStatusTest() throws ApiException {
        String version = null;
        StatusResponse response = api.engineStatus(version);
        // TODO: test validations
    }

    /**
     * Return the version of this Cromwell server
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void engineVersionTest() throws ApiException {
        String version = null;
        VersionResponse response = api.engineVersion(version);
        // TODO: test validations
    }

}
