# enabling version 2 turns github reviews on by default
version: 2
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: ':\+1:'
  reset_on_push:
    enabled: false
groups:
  reviewers:
    required: 2
    github_reviews:
      enabled: true
    author_approval:
      ignored: true
    users:
        - Horneth
        - cjllanwarne
        - geoffjentry
        - jsotobroad
        - katevoss
        - kcibul
        - kshakir
        - mcovarr
        - ruchim
        - danbills
