# enabling version 2 turns github reviews on by default
version: 2
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: ':\+1:'
  reset_on_push:
    enabled: false
groups:
  two_reviewers:
    required: 2
    github_reviews:
      enabled: true
    author_approval:
      ignored: true
    teams:
        - redteam
    conditions:
      files:
        exclude:
          - wdl/*
          - centaur/*
  one_reviewer:
    required: 1
    github_reviews:
      enabled: true
    author_approval:
      ignored: true
    teams:
        - redteam
    conditions:
      files:
        include:
          - wdl/*
          - centaur/*

