codecov:
  branch: develop

coverage:
  range: 0..100

  status:
    project:
      default:
        base: pr
        target: 0%
    patch:
      default:
        base: pr
        target: 0%

comment: off
