codecov:
  branch: develop

coverage:
  range: 50..75
  round: down
  precision: 2

  status:
    project:
      default:
        base: pr
        target: 50%
        threshold: 5%
    patch: # coverage report for the PR changes only
      default:
        base: pr
        target: 0%
        threshold: 0% # no required threshold for patch

comment: off

github_checks:
  annotations: false