codecov:
  status:
    project:
      default:
        base: pr
        target: 10%
        threshold: 5%
    patch:
      default:
        base: pr
        target: 10%
        threshold: 5%
comment: off
