#!/bin/bash

cd /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


cd /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution



oute9b3b629="${tmpDir}/out.$$" erre9b3b629="${tmpDir}/err.$$"
mkfifo "$oute9b3b629" "$erre9b3b629"
trap 'rm "$oute9b3b629" "$erre9b3b629"' EXIT
touch '/cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution/stdout' '/cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution/stderr'
tee '/cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution/stdout' < "$oute9b3b629" &
tee '/cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution/stderr' < "$erre9b3b629" >&2 &
(
cd /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution


echo "all dogs are good"
)  > "$oute9b3b629" 2> "$erre9b3b629"
echo $? > /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution
sync


)
mv /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution/rc.tmp /cromwell-executions/struct_literal/e9b3b629-b103-4bff-a504-b22a5b6f0a1d/call-create_dog/execution/rc
