version: '2.1'
services:
  cromwell:
    image: "broadinstitute/cromwell:${CROMWELL_TAG}"
    working_dir: /cromwell-working-dir
    volumes:
      - ./cromwell-executions:/cromwell-working-dir/cromwell-executions
      - ./compose/cromwell/app-config:/app-config
    links:
      - mysql-db
    depends_on:
      mysql-db:
        condition: service_healthy
    command: ["server"]
    environment:
      - JAVA_OPTS=-Dconfig.file=/app-config/cromwell-application.conf
  mysql-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=cromwell
      - MYSQL_DATABASE=cromwell_db
    volumes:
      - ./compose/mysql/init:/docker-entrypoint-initdb.d
      - ./compose/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "service", "mysql", "status"]
      interval: 2s
      timeout: 30s
      retries: 15
  lb:
    image: dockercloud/haproxy
    links:
      - cromwell
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:80
