package cromwell.backend.model

import cromwell.backend.model.OutputType.OutputType

/**
  * Defines an output type such as standard output or file.
  */
object OutputType extends Enumeration {
  type OutputType = Value
  val StdOutput, StdError, File = Value
}

/**
  * Represents basic data needed to execute a task in a defined backend.
  * @param name Task name.
  * @param user User who want to execute the task.
  * @param command Command to be executed.
  * @param commandArgs Arguments for the execution.
  * @param workingDir Task working directory.
  * @param outputs Outputs generated by the execution.
  * @param runtimeAttributes Configuration needed at runtime in order to execute a task.
  */
case class TaskDescriptor(name: String,
                          user: String,
                          command: String,
                          commandArgs: Option[Seq[String]],
                          workingDir: String,
                          outputs: Map[OutputType, String],
                          runtimeAttributes: Map[String, String])
