INSERT INTO TMP_SYMBOL (
  WORKFLOW_EXECUTION_UUID,
  SYMBOL_NAME,
  SYMBOL_SCOPE,
  WDL_VALUE,
  WDL_TYPE
)
  SELECT
    WORKFLOW_EXECUTION_UUID,
    s.NAME,
    s.SCOPE,
    s.WDL_VALUE,
    s.WDL_TYPE
  FROM SYMBOL s
    JOIN WORKFLOW_EXECUTION we ON
                                 we.WORKFLOW_EXECUTION_ID = s.WORKFLOW_EXECUTION_ID
  WHERE
    s.IO = 'OUTPUT' AND
    s.REPORTABLE_RESULT = 1;
