package cromwell.engine.workflow.lifecycle

case object EngineLifecycleActorAbortCommand

trait EngineLifecycleStateCompleteResponse

trait EngineLifecycleActorAbortedResponse extends EngineLifecycleStateCompleteResponse
