#!/bin/bash

cd /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


cd /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution



out38f3d028="${tmpDir}/out.$$" err38f3d028="${tmpDir}/err.$$"
mkfifo "$out38f3d028" "$err38f3d028"
trap 'rm "$out38f3d028" "$err38f3d028"' EXIT
touch '/cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution/stdout' '/cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution/stderr'
tee '/cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution/stdout' < "$out38f3d028" &
tee '/cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution/stderr' < "$err38f3d028" >&2 &
(
cd /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution


echo "all dogs are good"
)  > "$out38f3d028" 2> "$err38f3d028"
echo $? > /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution
sync


)
mv /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution/rc.tmp /cromwell-executions/struct_literal/38f3d028-9d44-4285-90e3-1cf1fc3f83a6/call-create_dog/execution/rc
