/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * The version of the OpenAPI document: 30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cromwell.client.api;

import cromwell.client.ApiCallback;
import cromwell.client.ApiClient;
import cromwell.client.ApiException;
import cromwell.client.ApiResponse;
import cromwell.client.Configuration;
import cromwell.client.Pair;
import cromwell.client.ProgressRequestBody;
import cromwell.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import cromwell.client.model.WorkflowDescription;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class WomtoolApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WomtoolApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WomtoolApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for describe
     * @param version Cromwell API Version (required)
     * @param workflowSource The workflow source file to submit for execution. Either workflow source or workflow url is required. (optional)
     * @param workflowUrl URL which points to the workflow. Either workflow source or workflow url is required. (optional)
     * @param workflowInputs JSON or YAML file containing the inputs as an object. (optional)
     * @param workflowType The workflow language for the file you submitted. Cromwell currently supports WDL and CWL. (optional)
     * @param workflowTypeVersion The specification version for the workflow language being used. For WDL, Cromwell currently supports draft-2 and 1.0. For CWL, Cromwell currently supports v1.0. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Workflow description. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call describeCall(String version, String workflowSource, String workflowUrl, String workflowInputs, String workflowType, String workflowTypeVersion, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/womtool/{version}/describe"
            .replaceAll("\\{" + "version" + "\\}", localVarApiClient.escapeString(version.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (workflowSource != null) {
            localVarFormParams.put("workflowSource", workflowSource);
        }

        if (workflowUrl != null) {
            localVarFormParams.put("workflowUrl", workflowUrl);
        }

        if (workflowInputs != null) {
            localVarFormParams.put("workflowInputs", workflowInputs);
        }

        if (workflowType != null) {
            localVarFormParams.put("workflowType", workflowType);
        }

        if (workflowTypeVersion != null) {
            localVarFormParams.put("workflowTypeVersion", workflowTypeVersion);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "googleoauth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call describeValidateBeforeCall(String version, String workflowSource, String workflowUrl, String workflowInputs, String workflowType, String workflowTypeVersion, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'version' is set
        if (version == null) {
            throw new ApiException("Missing the required parameter 'version' when calling describe(Async)");
        }
        

        okhttp3.Call localVarCall = describeCall(version, workflowSource, workflowUrl, workflowInputs, workflowType, workflowTypeVersion, _callback);
        return localVarCall;

    }

    /**
     * Machine-readable description of a workflow, including inputs and outputs
     * 
     * @param version Cromwell API Version (required)
     * @param workflowSource The workflow source file to submit for execution. Either workflow source or workflow url is required. (optional)
     * @param workflowUrl URL which points to the workflow. Either workflow source or workflow url is required. (optional)
     * @param workflowInputs JSON or YAML file containing the inputs as an object. (optional)
     * @param workflowType The workflow language for the file you submitted. Cromwell currently supports WDL and CWL. (optional)
     * @param workflowTypeVersion The specification version for the workflow language being used. For WDL, Cromwell currently supports draft-2 and 1.0. For CWL, Cromwell currently supports v1.0. (optional)
     * @return WorkflowDescription
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Workflow description. </td><td>  -  </td></tr>
     </table>
     */
    public WorkflowDescription describe(String version, String workflowSource, String workflowUrl, String workflowInputs, String workflowType, String workflowTypeVersion) throws ApiException {
        ApiResponse<WorkflowDescription> localVarResp = describeWithHttpInfo(version, workflowSource, workflowUrl, workflowInputs, workflowType, workflowTypeVersion);
        return localVarResp.getData();
    }

    /**
     * Machine-readable description of a workflow, including inputs and outputs
     * 
     * @param version Cromwell API Version (required)
     * @param workflowSource The workflow source file to submit for execution. Either workflow source or workflow url is required. (optional)
     * @param workflowUrl URL which points to the workflow. Either workflow source or workflow url is required. (optional)
     * @param workflowInputs JSON or YAML file containing the inputs as an object. (optional)
     * @param workflowType The workflow language for the file you submitted. Cromwell currently supports WDL and CWL. (optional)
     * @param workflowTypeVersion The specification version for the workflow language being used. For WDL, Cromwell currently supports draft-2 and 1.0. For CWL, Cromwell currently supports v1.0. (optional)
     * @return ApiResponse&lt;WorkflowDescription&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Workflow description. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkflowDescription> describeWithHttpInfo(String version, String workflowSource, String workflowUrl, String workflowInputs, String workflowType, String workflowTypeVersion) throws ApiException {
        okhttp3.Call localVarCall = describeValidateBeforeCall(version, workflowSource, workflowUrl, workflowInputs, workflowType, workflowTypeVersion, null);
        Type localVarReturnType = new TypeToken<WorkflowDescription>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Machine-readable description of a workflow, including inputs and outputs (asynchronously)
     * 
     * @param version Cromwell API Version (required)
     * @param workflowSource The workflow source file to submit for execution. Either workflow source or workflow url is required. (optional)
     * @param workflowUrl URL which points to the workflow. Either workflow source or workflow url is required. (optional)
     * @param workflowInputs JSON or YAML file containing the inputs as an object. (optional)
     * @param workflowType The workflow language for the file you submitted. Cromwell currently supports WDL and CWL. (optional)
     * @param workflowTypeVersion The specification version for the workflow language being used. For WDL, Cromwell currently supports draft-2 and 1.0. For CWL, Cromwell currently supports v1.0. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Workflow description. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call describeAsync(String version, String workflowSource, String workflowUrl, String workflowInputs, String workflowType, String workflowTypeVersion, final ApiCallback<WorkflowDescription> _callback) throws ApiException {

        okhttp3.Call localVarCall = describeValidateBeforeCall(version, workflowSource, workflowUrl, workflowInputs, workflowType, workflowTypeVersion, _callback);
        Type localVarReturnType = new TypeToken<WorkflowDescription>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
