#!/bin/bash

cd /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


cd /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution



oute0551f78="${tmpDir}/out.$$" erre0551f78="${tmpDir}/err.$$"
mkfifo "$oute0551f78" "$erre0551f78"
trap 'rm "$oute0551f78" "$erre0551f78"' EXIT
touch '/cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution/stdout' '/cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution/stderr'
tee '/cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution/stdout' < "$oute0551f78" &
tee '/cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution/stderr' < "$erre0551f78" >&2 &
(
cd /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution


echo "all dogs are good"
)  > "$oute0551f78" 2> "$erre0551f78"
echo $? > /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution
sync


)
mv /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution/rc.tmp /cromwell-executions/struct_literal/e0551f78-a899-4e5e-acde-2354f5a66641/call-create_dog/execution/rc
