package wdl.transforms

import wdl.transforms.draft2.wdlom2wom._
import wdl.transforms.wdlwom.WdlWomExpressionsAsInputsSpec

class WdlDraft2WomExpressionsAsInputsSpec extends WdlWomExpressionsAsInputsSpec
