name: 'Get Jira ID'
outputs:
  jira-id: ${{ steps.get-id.outputs.jira-id }}

runs:
  using: "composite" # <-- this allows these steps to be used by other workflows.
  steps:
    - name: "Get ID or fail"
      id: get-id
      uses: actions/github-script@v7
      with:
        script: |
          const title = context.payload.pull_request.title;
          const regex = /[A-Z][A-Z]+-\d+/;
          const match = title.match(regex)
          
          if (!match) {
            core.setFailed("PR title must contain a Jira tag");
          } else {
            console.log("Set output " + match[0]);
            core.setOutput("jira-id", match[0]);
          }
