#!/bin/bash

cd /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


cd /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution



out1d0336ca="${tmpDir}/out.$$" err1d0336ca="${tmpDir}/err.$$"
mkfifo "$out1d0336ca" "$err1d0336ca"
trap 'rm "$out1d0336ca" "$err1d0336ca"' EXIT
touch '/cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution/stdout' '/cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution/stderr'
tee '/cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution/stdout' < "$out1d0336ca" &
tee '/cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution/stderr' < "$err1d0336ca" >&2 &
(
cd /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution


echo "all dogs are good"
)  > "$out1d0336ca" 2> "$err1d0336ca"
echo $? > /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution
sync


)
mv /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution/rc.tmp /cromwell-executions/struct_literal/1d0336ca-0ffc-46ba-81e8-65f4da495896/call-create_dog/execution/rc
