package cromwell

import java.io.File
import java.util.UUID

import akka.actor.{ActorRef, ActorSystem}
import akka.pattern.ask
import akka.testkit._
import akka.util.Timeout
import com.typesafe.config.ConfigFactory
import cromwell.CromwellTestkitSpec._
import cromwell.binding._
import cromwell.binding.values.{WdlFile, WdlValue}
import cromwell.engine.ExecutionIndex.ExecutionIndex
import cromwell.engine._
import cromwell.engine.backend.StdoutStderr
import cromwell.engine.backend.local.LocalBackend
import cromwell.engine.db.DataAccess
import cromwell.engine.workflow.{WorkflowActor, WorkflowManagerActor}
import cromwell.engine.workflow.WorkflowActor
import cromwell.engine.workflow.WorkflowActor._
import cromwell.engine._
import cromwell.parser.BackendType
import cromwell.util.FileUtil._
import cromwell.util.SampleWdl
import org.scalatest.concurrent.ScalaFutures
import org.scalatest.{OneInstancePerTest, BeforeAndAfterAll, Matchers, WordSpecLike}

import scala.concurrent.Await
import scala.concurrent.duration._
import scala.language.postfixOps
import scala.reflect.ClassTag
import scala.util.matching.Regex

object CromwellTestkitSpec {
  val ConfigText =
    """
      |akka {
      |  loggers = ["akka.event.slf4j.Slf4jLogger", "akka.testkit.TestEventListener"]
      |  loglevel = "INFO"
      |  actor {
      |    debug {
      |       receive = on
      |    }
      |  }
      |}
    """.stripMargin

  val timeoutDuration = 10 seconds
  implicit val timeout = Timeout(timeoutDuration)
}

abstract class CromwellTestkitSpec(name: String) extends TestKit(ActorSystem(name, ConfigFactory.parseString(ConfigText)))
with DefaultTimeout with ImplicitSender with WordSpecLike with Matchers with BeforeAndAfterAll with ScalaFutures with OneInstancePerTest {

  def startingCallsFilter[T](callNames: String*)(block: => T): T =
    waitForPattern(s"starting calls: ${callNames.mkString(", ")}$$")(block)

  def waitForHandledMessage[T](named: String)(block: => T): T = {
    waitForHandledMessagePattern(s"^received handled message $named")(block)
  }

  def waitForHandledMessagePattern[T](pattern: String)(block: => T): T = {
    EventFilter.info(pattern = pattern, occurrences = 1).intercept {
      block
    }
  }

  val dataAccess = DataAccess()

  override protected def afterAll() = {
    super.afterAll()
    dataAccess.shutdown()
  }

  /**
   * Performs the following steps:
   *
   * <ol>
   * <li> Sends the specified message to the implicitly passed `ActorRef` via an `ask`.
   * <li> Collects the `Future[Any]` response.
   * <li> Downcasts the `Future[Any]` to a `Future[M]`.
   * <li> Issues a blocking `Await.result` on the `Future`, yielding an `M`.
   * </ol>
   *
   */
  def messageAndWait[M: ClassTag](message: AnyRef)(implicit actorRef: ActorRef): M = {
    val futureAny = actorRef ? message
    Await.result(futureAny.mapTo[M], timeoutDuration)
  }

  /**
   * Wait for exactly one occurrence of the specified pattern in the specified block.  The block
   * is in its own parameter list for usage syntax reasons.
   */
  def waitForPattern[T](pattern: String, occurrences: Int = 1)(block: => T): T = {
    EventFilter.info(pattern = pattern, occurrences = occurrences).intercept {
      within(timeoutDuration) {
        block
      }
    }
  }

  /**
   * Akka TestKit appears to be unable to match errors generated by `log.error(Throwable, String)` with the normal
   * `EventFilter.error(...).intercept {...}` mechanism since `EventFilter.error` forces the use of a dummy exception
   * that never matches a real exception.  This method works around that problem by building an `ErrorFilter` more
   * explicitly to allow the caller to specify a `Throwable` class.
   */
  def waitForErrorWithException[T](pattern: String, throwableClass: Class[_ <: Throwable] = classOf[Throwable], occurrences: Int = 1)(block: => T): T = {
    val regex = Right[String, Regex](pattern.r)
    ErrorFilter(throwableClass, source = None, message = regex, complete = false)(occurrences = occurrences).intercept {
      block
    }
  }

  def buildWorkflowDescriptor(sampleWdl: SampleWdl, runtime: String): WorkflowDescriptor = {
    buildWorkflowDescriptor(sampleWdl, runtime, UUID.randomUUID())
  }

  def buildWorkflowDescriptor(sampleWdl: SampleWdl, runtime: String, uuid: UUID): WorkflowDescriptor = {
    val source = sampleWdl.wdlSource(runtime)
    val namespace = NamespaceWithWorkflow.load(source, BackendType.LOCAL)
    val coercedInputs = namespace.coerceRawInputs(sampleWdl.rawInputs).get
    val declarations = namespace.staticDeclarationsRecursive(coercedInputs).get
    val inputs = coercedInputs ++ declarations
    WorkflowDescriptor(WorkflowId(uuid), namespace, source, sampleWdl.wdlJson, inputs)
  }

  private def buildFsmWorkflowActor(sampleWdl: SampleWdl, runtime: String) = {
    TestFSMRef(new WorkflowActor(buildWorkflowDescriptor(sampleWdl, runtime), new LocalBackend, dataAccess))
  }

  private def buildWorkflowManagerActor(sampleWdl: SampleWdl, runtime: String) = {
    TestActorRef(new WorkflowManagerActor(dataAccess, new LocalBackend))
  }

  def runWdl(fsm: TestFSMRef[WorkflowState, WorkflowActor.WorkflowFailure, WorkflowActor],
             eventFilter: EventFilter,
             expectedOutputs: Map[FullyQualifiedName, WdlValue] = Map.empty,
             terminalState: WorkflowState = WorkflowSucceeded): Unit = {
    assert(fsm.stateName == WorkflowSubmitted)
    eventFilter.intercept {
      fsm ! WorkflowActor.Start
      within(timeoutDuration) {
        awaitCond(fsm.stateName == WorkflowRunning)
        awaitCond(fsm.stateName == terminalState)

        if (terminalState == WorkflowSucceeded)
          fsm.stateData should be(WorkflowActor.NoFailureMessage)

        if (terminalState == WorkflowFailed)
          fsm.stateData.isInstanceOf[WorkflowActor.FailureMessage] shouldEqual true

        val outputs = fsm.ask(WorkflowActor.GetOutputs).mapTo[WorkflowOutputs].futureValue

        expectedOutputs foreach { case (outputFqn, expectedValue) =>
          val actualValue = outputs.getOrElse(outputFqn, throw new RuntimeException(s"Output $outputFqn not found"))

          // Not great, but this is so we can test matching WdlFile against WdlFile more easily
          expectedValue match {
            case expectedFile: WdlFile if actualValue.isInstanceOf[WdlFile] =>
              val actualFile = actualValue.asInstanceOf[WdlFile]
              actualFile.value.toString.endsWith(expectedFile.value.toString) shouldEqual true
            case _ =>
              actualValue shouldEqual expectedValue
          }
        }
      }
    }
  }

  def runWdlWithWorkflowManagerActor(wma: TestActorRef[WorkflowManagerActor], submitMsg: WorkflowManagerActor.SubmitWorkflow, eventFilter: EventFilter, fqn: FullyQualifiedName, index: ExecutionIndex, stdout: Option[String], stderr: Option[String]) = {
    eventFilter.intercept {
      within(timeoutDuration) {
        val workflowId = Await.result(wma.ask(submitMsg).mapTo[WorkflowId], timeoutDuration)
        def workflowStatus = Await.result(wma.ask(WorkflowManagerActor.WorkflowStatus(workflowId)).mapTo[Option[WorkflowState]], timeoutDuration)
        awaitCond(workflowStatus.contains(WorkflowSucceeded))
        val standardStreams = Await.result(wma.ask(WorkflowManagerActor.CallStdoutStderr(workflowId, fqn, index)).mapTo[StdoutStderr], timeoutDuration)
        stdout foreach { _ shouldEqual new File(standardStreams.stdout.value).slurp}
        stderr foreach { _ shouldEqual new File(standardStreams.stderr.value).slurp}
      }
    }
  }

  /* TODO: make the `eventFilter` parameter able to accept a `Seq[EventFilter]` */
  def runWdlAndAssertOutputs(descriptor: WorkflowDescriptor, eventFilter: EventFilter, expectedOutputs: Map[FullyQualifiedName, WdlValue]): Unit = {
    val fsm = TestFSMRef(new WorkflowActor(descriptor, new LocalBackend, dataAccess))
    runWdl(fsm, eventFilter, expectedOutputs)
  }

  def runWdlAndAssertOutputs(sampleWdl: SampleWdl, eventFilter: EventFilter, runtime: String = "", expectedOutputs: Map[FullyQualifiedName, WdlValue] = Map.empty, terminalState: WorkflowState = WorkflowSucceeded): Unit = {
    val fsm = buildFsmWorkflowActor(sampleWdl, runtime)
    runWdl(fsm, eventFilter, expectedOutputs, terminalState)
  }

  def runWdlAndAssertStdoutStderr(sampleWdl: SampleWdl, eventFilter: EventFilter, fqn: FullyQualifiedName, index: ExecutionIndex, runtime: String = "", stdout: Option[String] = None, stderr: Option[String] = None) = {
    val actor = buildWorkflowManagerActor(sampleWdl, runtime)
    val submitMessage = WorkflowManagerActor.SubmitWorkflow(sampleWdl.wdlSource(runtime), sampleWdl.wdlJson, sampleWdl.rawInputs)
    runWdlWithWorkflowManagerActor(actor, submitMessage, eventFilter, fqn, index, stdout, stderr)
  }
}
