name: 'Basic Unit Test'

#The goal of this Github Action is to verify that is is possible to compile cromwell (enough) to run a simple unit test.

#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} running Basic Unit Test.

#What will trigger the workflow to run. 
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push:
  pull_request: 

permissions: 
  contents: read

jobs:
  build-and-test:
    strategy:
      fail-fast: false  
      matrix:
        sbtSubProject: [awsBackend,
        awsS3FileSystem,
        azureBlobFileSystem,
        backend,
        centaur,
        cloud-nio-impl-drs,
        cloud-nio-impl-ftp,
        cloud-nio-spi,
        cloud-nio-util,
        cloudSupport,
        common,
        core,
        cromiam,
        cromwell-drs-localizer,
        cromwellApiClient,
        databaseMigration,
        databaseSql,
        dockerHashing,
        drsFileSystem,
        engine,
        ftpFileSystem,
        gcsFileSystem,
        googlePipelinesCommon,
        googlePipelinesV2Alpha1,
        googlePipelinesV2Beta,
        httpFileSystem,
        languageFactoryCore,
        perf,
        server,
        services,
        sfsBackend,
        sraFileSystem,
        tesBackend,
        wdlBiscayneLanguageFactory,
        wdlDraft2LanguageFactory,
        wdlDraft3LanguageFactory,
        wdlModelBiscayne,
        wdlModelDraft2,
        wdlModelDraft3,
        wdlNewBaseTransforms,
        wdlSharedModel,
        wdlSharedTransforms,
        wdlTransformsBiscayne,
        wdlTransformsDraft2,
        wdlTransformsDraft3,
        wes2cromwell,
        wom,
        womtool]
    runs-on: ubuntu-latest #Note: This action is using a Github free runner, rather than a Broad self-hosted one. This is because the Broad ones don't have sbt installed by default.
    #name: ${{ matrix.sbtSubProject }} Unit Tests
    steps:
    - uses: actions/checkout@v3
      name: Checkout Coursier Cache
    - uses: coursier/cache-action@v6  
      name: Enable Coursier Cache

    - name: Git secrets setup #The Broad requires git-secrets be setup. The Secrets check below veritfies that the setup worked.
      run: |
        git clone https://github.com/awslabs/git-secrets.git ~/git-secrets
        cd ~/git-secrets
        git checkout ad82d68ee924906a0401dfd48de5057731a9bc84
        sudo make install
    - name: Secrets check
      run: |
        sudo ln -s "$(which echo)" /usr/local/bin/say
        ./minnie-kenny.sh --force
        git secrets --scan-history

    - name: Clone Cromwell
      uses: actions/checkout@v3
      with:
        repository: broadinstitute/cromwell
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: sbt
    - name: Run tests #Invoke SBT with an argument asking it to run a specific test in a specific sbt project. 
      run: |
        set -e
        sbt "${{ matrix.sbtSubProject }}/test"