name: 'Basic Unit Test'

#The goal of this Github Action is to verify that is is possible to compile cromwell (enough) to run a simple unit test.

#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} running Basic Unit Test.

#What will trigger the workflow to run. 
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push:
  pull_request: 

permissions: 
  contents: read

jobs:
  build-and-test:
    name: SBT VersionUtilSpec Unit Test
    runs-on: self-hosted # Faster machines; see https://github.com/broadinstitute/cromwell/settings/actions/runners
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
    - name: Clone Cromwell
      uses: actions/checkout@v3
      with:
        repository: broadinstitute/cromwell
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
        path: cromwell
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Run tests #Invoke SBT with an argument asking it to run a specific test in a specific sbt project. 
      run: |
        set -e
        cd cromwell
        sbt "common/testOnly common.util.VersionUtilSpec"
