name: 'Centaur Integration Tests'

#This github action runs all of Cromwell's integration tests.

#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} Centaur Testing.

#What will trigger the workflow to run. 
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push: #git push

permissions: 
  contents: read

jobs:
  centaur-tests:
    strategy:
      fail-fast: false #disabling fail-fast means that even if one test fails, the others will still try to complete.
      #Each entry below is a single integration test that lives in /src/ci/bin/. 
      #Each will be launched on its own runner so they can occur in parallel.
      matrix:
        include:
          - build_type: centaurPapiV2beta
            build_mysql: 5.7
          - build_type: dbms
          - build_type: centaurTes
            build_mysql: 5.7
          - build_type: centaurEngineUpgradeLocal
          - build_type: centaurLocal
            build_mysql: 5.7
          - build_type: centaurLocal
            build_postgresql: 11.3
          - build_type: checkPublish
          - build_type: centaurAws
            build_mysql: 5.7
          - build_type: centaurDummy
            build_mysql: 5.7
          - build_type: centaurHoricromtalPapiV2beta
            build_mysql: 5.7
          - build_type: centaurSlurm
            build_mysql: 5.7
          - build_type: horicromtalDeadlock
          - build_type: singleWorkflowRunner
          - build_type: referenceDiskManifestBuilderApp
          - build_type: centaurLocal
            build_mariadb: 10.3
    env:
      BUILD_NAME: ${{ matrix.build_type }}
      BUILD_TYPE: ${{ matrix.build_type }} #intentionally duplicated variable
      BUILD_MYSQL: ${{ matrix.build_mysql }}
      BUILD_POSTGRESQL: ${{ matrix.build_postgresql }}
      BUILD_MATRIADB: ${{ matrix.build_mariadb }}
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID_CI }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID_CI }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3 # checkout the cromwell repo
    - uses: ./.github/set_up_cromwell_action #This github action will set up git-secrets, caching, java, and sbt.
      with:
        cromwell_repo_token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
    #This script bascially just looks up another script to run, assuming that the other script's filename is:
    #src/ci/bin/test${BUILD_TYPE}.sh. The first letter of the BUILD_TYPE is automatically capitalized when looking.
    - name: Run Centaur Test
      run: |
        set -e
        echo Running test.sh
        ./src/ci/bin/test.sh
