name: 'Centaur Integration Tests'

#This github action runs all of Cromwell's unit tests.

#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} running Centaur Integration Tests.

#What will trigger the workflow to run. 
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push:

permissions: 
  contents: read

jobs:
  centaur-tests: 
    env:
      BUILD_NAME: singleWorkflowRunner
      BUILD_TYPE: singleWorkflowRunner
      BUILD_MYSQL: 5.7
      VAULT_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3 # checkout the cromwell repo
    - uses: ./.github/set_up_cromwell_action #Exectute this reusable github action. It will set up java/sbt/git-secrets/cromwell.
      with:
        cromwell_repo_token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
    - name: Run Centaur Test
      run: |
        set -e
        echo Running test.sh
        echo $BUILD_NAME
        echo $BUILD_TYPE
        ./src/ci/bin/test.sh
