name: 'Centaur Integration Tests'

#This github action runs all of Cromwell's unit tests.

#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} running Centaur Integration Tests.

#What will trigger the workflow to run. 
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push:

permissions: 
  contents: read

jobs:
  centaur-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_type: centaurPapiV2beta
            build_mysql: 5.7
          - build_type: dbms
          - build_type: centaurTes
            build_mysql: 5.7
          - build_type: centaurEngineUpgradeLocal
          - build_type: centaurLocal
            build_mysql: 5.7
          - build_type: centaurLocal
            build_postgresql: 11.3
          - build_type: checkPublish

    env:
      BUILD_NAME: ${{ matrix.build_type }}
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_MYSQL: ${{ matrix.build_mysql }}
      BUILD_POSTGRESQL: ${{ matrix.build_postgresql }}
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID_CI }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID_CI }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3 # checkout the cromwell repo
    - uses: ./.github/set_up_cromwell_action #Exectute this reusable github action. It will set up java/sbt/git-secrets/cromwell.
      with:
        cromwell_repo_token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
    - name: Run Centaur Test
      run: |
        set -e
        echo Running test.sh
        ./src/ci/bin/test.sh
