name: 'Centaur Integration Tests'

#This github action runs all of Cromwell's unit tests.

#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} running Centaur Integration Tests.

#What will trigger the workflow to run. 
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push:

permissions: 
  contents: read

jobs:
  build-and-test: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # checkout the cromwell repo
    - uses: ./.github/set_up_cromwell_action #Exectute this reusable github action. It will set up java/sbt/git-secrets/cromwell.
      with:
        cromwell_repo_token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
  
    #Invoke SBT to build a cromwell jar
    - name: Compile Cromwell
      run: |
        sbt assembly

    #Start the database that cromwell depends on
    #- name: Launch Docker MySQL Database
    #  run: |
    #    ./processes/release_processes/scripts/start_publish_mysql_docker.sh

    #The name of the cromwell jar depends on its version number. Find the path to the jar we'd like to test
    - name: Run Integration Test
      run: |
        exec "./src/ci/bin/testCentaurLocal.sh"
      env:
        CROMWELL_BUILD_PROVIDER: GITHUB_ACTIONS
        CROMWELL_BUILD_HOME_DIRECTORY: "$(pwd)"
        CROMWELL_BUILD_ROOT_DIRECTORY: "$(pwd)"
        CROMWELL_BUILD_LOG_DIRECTORY: "${CROMWELL_BUILD_ROOT_DIRECTORY}/target/ci/logs"
        CROMWELL_BUILD_CROMWELL_LOG: "${CROMWELL_BUILD_LOG_DIRECTORY}/cromwell.log"
        CROMWELL_BUILD_DOCKER_DIRECTORY: "${CROMWELL_BUILD_ROOT_DIRECTORY}/src/ci/docker-compose"
        CROMWELL_BUILD_SCRIPTS_DIRECTORY: "${CROMWELL_BUILD_ROOT_DIRECTORY}/src/ci/bin"
        CROMWELL_BUILD_RESOURCES_SOURCES: "${CROMWELL_BUILD_ROOT_DIRECTORY}/src/ci/resources"
        CROMWELL_BUILD_RESOURCES_DIRECTORY: "${CROMWELL_BUILD_ROOT_DIRECTORY}/target/ci/resources"
        CROMWELL_BUILD_GIT_SECRETS_DIRECTORY: "${CROMWELL_BUILD_RESOURCES_DIRECTORY}/git-secrets"
        CROMWELL_BUILD_GIT_SECRETS_COMMIT: "ad82d68ee924906a0401dfd48de5057731a9bc84"
        CROMWELL_BUILD_WAIT_FOR_IT_FILENAME: "wait-for-it.sh"
        CROMWELL_BUILD_WAIT_FOR_IT_BRANCH: "db049716e42767d39961e95dd9696103dca813f1"
        CROMWELL_BUILD_WAIT_FOR_IT_URL: "https://raw.githubusercontent.com/vishnubob/wait-for-it/${CROMWELL_BUILD_WAIT_FOR_IT_BRANCH}/${CROMWELL_BUILD_WAIT_FOR_IT_FILENAME}"
        CROMWELL_BUILD_WAIT_FOR_IT_SCRIPT: "${CROMWELL_BUILD_RESOURCES_DIRECTORY}/${CROMWELL_BUILD_WAIT_FOR_IT_FILENAME}"
        CROMWELL_BUILD_VAULT_ZIP: "${CROMWELL_BUILD_RESOURCES_DIRECTORY}/vault.zip"
        CROMWELL_BUILD_VAULT_EXECUTABLE: "${CROMWELL_BUILD_RESOURCES_DIRECTORY}/vault"
        CROMWELL_BUILD_EXIT_FUNCTIONS: "${CROMWELL_BUILD_RESOURCES_DIRECTORY}/cromwell_build_exit_functions.$$"

