name: Make publish PRs

on:
  workflow_dispatch:
    inputs:
      old_cromwell_version:
        description: 'What version of Cromwell to update from'
        required: true
      new_cromwell_version:
        description: 'What version of Cromwell to update to'
        required: true
      jira_ticket:
        description: 'The JIRA ticket to link the update PR to'
        required: true

jobs:
  make-firecloud-develop-pr:
    name: Create firecloud-develop PR
    runs-on: self-hosted # Faster machines; see https://github.com/broadinstitute/cromwell/settings/actions/runners
    steps:
      - name: Clone firecloud-develop
        uses: actions/checkout@v2
        with:
          repository: broadinstitute/firecloud-develop
          token: ${{ secrets.BROADBOT_GITHUB_TOKEN }} # Has to be set at checkout AND later when pushing to work
          path: firecloud-develop
      - name: Update & push to firecloud-develop
        id: update-and-push
        env:
          BROADBOT_GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
        run: |
          cd firecloud-develop
          JIRA_TICKET=${{ github.event.inputs.jira_ticket }}
          OLD_CROMWELL_V=${{ github.event.inputs.old_cromwell_version }}
          NEW_CROMWELL_V=${{ github.event.inputs.new_cromwell_version }}
          NEW_BRANCH_NAME="${JIRA_TICKET}_cromwell_${NEW_CROMWELL_V}"
          TEMP=$(mktemp)
          git checkout -b "${NEW_BRANCH_NAME}"
          SED_STRING="s/${OLD_CROMWELL_V}/${NEW_CROMWELL_V}/g"
          FILES=( "base-configs/cromwell/cromwell.conf.ctmpl" "run-context/fiab/scripts/FiaB_images.env" )
          for i in "${FILES[@]}"
          do
            echo "Updating ${i}"
            sed "${SED_STRING}" ${i} > ${TEMP}
            mv ${TEMP} ${i}
            git add ${i}
          done
          echo "Pushing to firecloud-develop branch ${NEW_BRANCH_NAME}"
          git config --global user.name "broadbot"
          git config --global user.email "broadbot@broadinstitute.org"
          git commit -m "Updating Cromwell version to ${NEW_CROMWELL_V}"
          git push https://broadbot:$BROADBOT_GITHUB_TOKEN@github.com/broadinstitute/firecloud-develop.git ${NEW_BRANCH_NAME}
          echo ::set-output name=NEW_BRANCH_NAME::${NEW_BRANCH_NAME}
      - name: Create firecloud-develop PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
          script: |
            const result = await github.rest.pulls.create({
              title: '${{ github.event.inputs.jira_ticket }}: Update Cromwell version to ${{ github.event.inputs.new_cromwell_version }}',
              owner: 'broadinstitute',
              repo: 'firecloud-develop',
              head: '${{ steps.update-and-push.outputs.NEW_BRANCH_NAME }}',
              base: 'dev',
              body: [
                'This PR is auto-generated by',
                '[Cromwell actions/make_publish_prs](https://github.com/broadinstitute/cromwell/blob/develop/.github/workflows/make_publish_prs.yml), using',
                '[github actions/github-script](https://github.com/actions/github-script).',
                '',
                'It updates cromwell from version ${{ github.event.inputs.old_cromwell_version }} to ${{ github.event.inputs.new_cromwell_version }}.'
              ].join('\n')
            });

