#This github action runs all of Cromwell's integration tests nightly.
name: 'Nightly Integration Tests'

#This is what shows up in the github workflows page as the title.
run-name: Nightly ${{ github.actor }} Integration Testing.

#What will trigger the workflow to run.
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 1-5'

permissions:
  contents: read

# Use if as arg to only send slack notifications on nightly
jobs:
  integration-tests:
    uses: broadinstitute/cromwell/.github/workflows/integration_tests.yml@90cc46dfa1d1ed75300f0ef25607076c08151b09
    with:
      target-branch: 'develop'
      slack-alert: true
    secrets: inherit
