name: Release Community Cromwell

on:
  workflow_dispatch: 

jobs:
  cromwell-release:
    name: Release Community Cromwell
    runs-on: ubuntu-latest
    steps:
    - uses: sbt/setup-sbt@v1
    - name: Find Cromwell release number
      run: |
        set -e
        previous_version=$(curl -X GET https://api.github.com/repos/broadinstitute/cromwell/releases/latest | jq .tag_name | xargs)
        if ! [[ "${previous_version}" =~ ^[0-9][0-9]+$ ]]; then
          exit 1
        fi
        echo "RELEASE_VERSION=$((previous_version + 1))" >> $GITHUB_ENV
        echo "NEXT_VERSION=$((previous_version + 2))" >> $GITHUB_ENV
    - name: Clone Cromwell
      uses: actions/checkout@v4
      with:
        repository: jgainerdewar/cromwell
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }} # Has to be set at checkout AND later when pushing to work
        path: cromwell
        ref: develop
        fetch-depth: 0
    - name: Merge to master and tag release
      run: |
        cd cromwell

        git config --global user.name "broadbot"
        git config --global user.email "broadbot@broadinstitute.org"

        echo 'Merge develop into master'
        git checkout --track origin/master
        git merge --no-edit develop

        echo 'Tag the release'
        git tag --message=${RELEASE_VERSION} ${RELEASE_VERSION}
    - name: Update develop with new version
      run: |
        cd cromwell
        git checkout develop
        sed -i -e '/cromwellVersion[[:space:]]=/s/[0-9][0-9]*/${NEXT_VERSION}/' project/Version.scala
        git add project/Version.scala
        git diff-index --quiet HEAD \
        || git commit --message "Update cromwell version from ${RELEASE_VERSION} to ${NEXT_VERSION}"
    - name: Build new release
      run: |
        cd cromwell
        git checkout master
        # Use sbt.server.forcestart to workaround https://github.com/sbt/sbt/issues/6101
        echo 'Assemble jars for cromwell and womtool'
        sbt \
        -Dsbt.server.forcestart=true \
        -Dproject.version=${RELEASE_VERSION} \
        -Dproject.isSnapshot=false \
        server/assembly \
        womtool/assembly
    - name: Prepare release notes
      run: |
        cd cromwell
        sed -n '/## ~{currentReleaseVersion}/,/## [0-9]/p' CHANGELOG.md \
        | sed '$d' \
        > changelog.txt
    # - name: Push changes to origin
    #   run: |
    #     cd cromwell
    #     git push origin master develop ${RELEASE_VERSION}
    # - name: Create Github release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     body_path: changelog.txt
    #     tag_name: ${{ env.RELEASE_VERSION }}
    #     token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
    #     files: |
    #       server/target/scala-2.13/cromwell-${{ env.RELEASE_VERSION }}.jar
    #       womtool/target/scala-2.13/womtool-${{ env.RELEASE_VERSION }}.jar

# TODO build and push Cromwell docker image
