name: sbt-tests
on: [pull_request]

jobs:
  build-and-test:
    name: Build and run SBT tests
    runs-on: self-hosted # Faster machines; see https://github.com/broadinstitute/cromwell/settings/actions/runners
    steps:
    - name: Clone Cromwell
      uses: actions/checkout@v2
      with:
        repository: broadinstitute/cromwell
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }} # Has to be set at checkout AND later when pushing to work
        path: cromwell
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Build Cromwell Docker
      run: |
        set -e
        cd cromwell
        sbt \
          -Dsbt.supershell=false \
          -Dakka.test.timefactor=10 \
          -Dbackend.providers.Local.config.filesystems.local.localization.0=copy \
          test
