name: dsp-appsec-shiftleft
on: [pull_request]

jobs:
  shiftleft:
    name: ShiftLeft static security analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - env:
          SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
          SHIFTLEFT_TOKEN: ${{ secrets.SHIFTLEFT_TOKEN }}
        run: |
          curl https://cdn.shiftleft.io/download/sl > $HOME/sl && chmod +x $HOME/sl
          $HOME/sl auth --org "${SHIFTLEFT_ORG_ID}" --token "${SHIFTLEFT_TOKEN}"
