name: 'Build Cromwell Test'


#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} is testing out workflows.

#What triggers the workflow to run.
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push: #On push to specified branches. 
    branches:
      - travis_to_workflows_test

permissions: 
  contents: read

#Global environment variables.
env:
  BUILD_TYPE: centaurAws
  BUILD_MYSQL: 5.7

jobs:
  check-bats-version: #Sanity check not related to Cromwell. Should always pass. 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "Build Type $BUILD_TYPE"
      - run: echo "Build MySQL $BUILD_MYSQL"
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: bash -c 'echo $BASH_VERSION'
      - run: src/ci/bin/test.sh
  