name: travis-to-github-test
run-name: ${{ github.actor }} is testing out workflows. 
on:
  push:
    branches:
      -travis_to_workflows_test

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v