name: 'Basic Unit Test'

#The goal of this Github Action is to verify that 

#This is what shows up in the github workflows page as the title. 
run-name: ${{ github.actor }} running Basic Unit Test.

#What triggers the workflow to run.
on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push:
  pull_request: 

permissions: 
  contents: read

#Global environment variables.
env:
  #BUILD_TYPE: centaurAws
  #BUILD_MYSQL: 5.7

jobs:
  build-and-test:
    name: SBT VersionUtilSpec testgig
    runs-on: self-hosted # Faster machines; see https://github.com/broadinstitute/cromwell/settings/actions/runners
    steps:
    - name: Clone Cromwell
      uses: actions/checkout@v3
      with:
        repository: broadinstitute/cromwell
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }} # Has to be set at checkout AND later when pushing to work
        path: cromwell
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: adopt@1.11
    - name: Run tests
      run: |
        set -e
        cd cromwell
        sbt "test:testOnly common.util.VersionUtilSpec"